DROP TABLE IF EXISTS CONVERSION_HISTORY;
  
CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
   base VARCHAR(250) NOT NULL,
  symbols VARCHAR(250) NOT NULL,
   history_date date NOT NULL,
 
  rate NUMBER(250,10) NOT NULL
);
